# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phn_no', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phn_no', models.IntegerField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('med_name', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=30)),
            ],
        ),
    ]
