# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pharma', '0011_auto_20171109_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='d_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phn_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
