# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pharma', '0012_auto_20171110_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='d_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
    ]
