# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pharma', '0015_auto_20171111_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phn_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
