# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pharma', '0016_auto_20171111_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='c_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='m_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='p_id',
            field=models.IntegerField(unique=True),
        ),
    ]
